version: '3.8'


services:
  
  web:
    build: ./dcbeat
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    volumes:
      - ./dcbeat:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  redis:
    image: redis:alpine
  
  celery:
    build: ./dcbeat
    command: celery -A dcbeat worker -l info
    volumes:
      - ./dcbeat:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
    
  celey-beat:
    build: ./dcbeat
    command: celery -A dcbeat beat -l info
    volumes:
      - ./dcbeat:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
    